// Importing necessary styles and fonts
import './normalize.css'      // Resets and normalizes default browser styles.
import './globals.css'        // Global custom styles for the application.
import { Inter } from 'next/font/google'  // Imports the 'Inter' font from Google's font module for Next.js

// Configure the 'Inter' font with the 'latin' subset.
const interFontConfig = Inter({ subsets: ['latin'] })

// Metadata for the application.
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * RootLayout Component.
 * A layout wrapper for the main application which ensures consistent layout and styles.
 *
 * @param {Object} props - Component props.
 * @param {React.ReactNode} props.children - Children components or nodes.
 * @returns {JSX.Element} The rendered JSX element.
 */
export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={interFontConfig.className}>
        <div className="main-card">
          {children}
        </div>  
      </body>
    </html>
  )
}
