// Importing necessary styles and fonts.

// Import the 'normalize.css' which provides CSS rules to reset and normalize default browser styles.
import './normalize.css' 
// Import the global styles that define the basic styling for the whole application.
import './globals.css'        
// Use the 'next/font' module from Next.js to import the 'Inter' font from Google Fonts.
import { Inter } from 'next/font/google'  

// Configure the 'Inter' font. The configuration includes specifying the 'latin' subset to reduce the size and improve loading times.
const interFontConfig = Inter({ subsets: ['latin'] })

// Metadata for the application. This can be utilized in the document's head for SEO and other purposes.
export const metadata = {
  title: 'Create Next App',  // Default title of the application.
  description: 'Generated by create next app',  // Short description about the application.
}

/**
 * RootLayout Component.
 * This is a layout component that wraps around the main application. It ensures that the application
 * maintains consistent layout and styles across different pages and components. 
 * The component also sets the 'lang' attribute to 'en' for the document, and utilizes the 'Inter' font for styling.
 *
 * @param {Object} props - The properties passed to the component.
 * @param {React.ReactNode} props.children - Any child components or content to be displayed inside the layout.
 * @returns {JSX.Element} A JSX element that renders the provided children within a structured layout.
 */
export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">  {/* Set the document language to English. */}
      <body className={interFontConfig.className}>  {/* Apply the 'Inter' font styles to the document body. */}
        <div className="main-card">  {/* A container for the main content of the application. */}
          {children}  {/* Render the child components or content passed to the layout. */}
        </div>  
      </body>
    </html>
  )
}
